Stock.create(name:'Agilent Technologies' , code: 'A')
Stock.create(name:'Alcoa' , code: 'AA')
Stock.create(name:'American Airlines' , code: 'AAL')
Stock.create(name:'Advance Auto Parts' , code: 'AAP')
Stock.create(name:'Apple' , code: 'AAPL')
Stock.create(name:'Actavis' , code: 'ACT')
Stock.create(name:'Analog Devices' , code: 'ADI')
Stock.create(name:'American Electric Power' , code: 'AEP')
Stock.create(name:'Assurant' , code: 'AIZ')
Stock.create(name:'Amazon' , code: 'AMZN')
Stock.create(name:'American Express' , code: 'AXP')
Stock.create(name:'Alibaba Group Holding' , code: 'BABA')
Stock.create(name:'Cheesecake Factory' , code: 'CAKE')
Stock.create(name:'Caterpillar' , code: 'CAT')
Stock.create(name:'Chipotle Mexican Grill' , code: 'CMG')
Stock.create(name:'Cabot Oil & Gas' , code: 'COG')
Stock.create(name:'Columbia Sportswear' , code: 'COLM')
Stock.create(name:'Costco' , code: 'COST')
Stock.create(name:'Cisco' , code: 'CSCO')
Stock.create(name:'Cypress Semiconductor' , code: 'CY')
Stock.create(name:'CyberArk Software' , code: 'CYBR')
Stock.create(name:'Cracker Barrel Old Country Store' , code: 'CBRL')
Stock.create(name:'Chesapeake Energy' , code: 'CHK')
Stock.create(name:'Chipotle Mexican Grill' , code: 'CMG')
Stock.create(name:'Diebold' , code: 'DBD')
Stock.create(name:'Deere & Co' , code: 'DE')
Stock.create(name:'Deckers Outdoor' , code: 'DECK')
Stock.create(name:'DineEquity' , code: 'DIN')
Stock.create(name:'Walt Disney' , code: 'DIS')
Stock.create(name:'DISH Network' , code: 'DISH')
Stock.create(name:'Dow Chemical' , code: 'DOW')
Stock.create(name:'DreamWorks Animation' , code: 'DWA')
Stock.create(name:'Ebay' , code: 'EBAY')
Stock.create(name:'Estee Lauder' , code: 'EL')
Stock.create(name:'EOG Resources' , code: 'EOG')
Stock.create(name:'Express Scripts Holding' , code: 'ESRX')
Stock.create(name:'ENSCO PLC' , code: 'ESV')
Stock.create(name:'Ethan Allen Interiors' , code: 'ETH')
Stock.create(name:'Exelon' , code: 'EXC')
Stock.create(name:'Edwards Lifesciences' , code: 'EW')
Stock.create(name:'Ford Motor' , code: 'F')
Stock.create(name:'Fastenal' , code: 'FAST')
Stock.create(name:'Facebook' , code: 'FB')
Stock.create(name:'FireEye' , code: 'FEYE')
Stock.create(name:'Finisar' , code: 'FNSR')
Stock.create(name:'Fossil Group' , code: 'FOSL')
Stock.create(name:'First Solar' , code: 'FSLR')
Stock.create(name:'Fortinet' , code: 'FTNT')
Stock.create(name:'Gilead Sciences' , code: 'GILD')
Stock.create(name:'Gold' , code: 'GOLD')
Stock.create(name:'Keurig Green Mountain' , code: 'GMCR')
Stock.create(name:'GoPro' , code: 'GPRO')
Stock.create(name:'Garmin' , code: 'GRMN')
Stock.create(name:'Goodyear Tire' , code: 'GT')
Stock.create(name:'Blackhawk Network Holdings' , code: 'HAWK')
Stock.create(name:'Honda Motor' , code: 'HMC')
Stock.create(name:'Hewlett-Packard' , code: 'HPQ')
Stock.create(name:'' , code: 'HPW')
Stock.create(name:'Henry Schein' , code: 'HSIC')
Stock.create(name:'Hershey' , code: 'HSY')
Stock.create(name:'iShares Nasdaq Biotechnology' , code: 'IBB')
Stock.create(name:'International Business Machines' , code: 'IBM')
Stock.create(name:'Integrated Device Technology' , code: 'IDTI')
Stock.create(name:'Isis Pharmaceuticals' , code: 'ISI')
Stock.create(name:'Isis Pharmaceuticals' , code: 'ISIS')
Stock.create(name:'Jack in the Box' , code: 'JACK')
Stock.create(name:'Kellogg' , code: 'K')
Stock.create(name:'Kimberly-Clark' , code: 'KMB')
Stock.create(name:'Kinder Morgan' , code: 'KMI')
Stock.create(name:'Michael Kors Holdings' , code: 'KORS')
Stock.create(name:'Kroger' , code: 'KR')
Stock.create(name:'L Brands' , code: 'LB')
Stock.create(name:'Lenovo' , code: 'LNVGY')
Stock.create(name:'El Pollo Loco Holdings' , code: 'LOCO')
Stock.create(name:'La Quinta Holdings' , code: 'LQ')
Stock.create(name:'Southwest Airlines' , code: 'LUV')
Stock.create(name:'Macy' , code: 'M')
Stock.create(name:'Mobileye' , code: 'MBLY')
Stock.create(name:'Magnum Hunter Resources' , code: 'MHR')
Stock.create(name:'Monster Beverage' , code: 'MNST')
Stock.create(name:'Morgan Stanley' , code: 'MS')
Stock.create(name:'Microsemi' , code: 'MSCC')
Stock.create(name:'Microsoft' , code: 'MSFT')
Stock.create(name:'Micron Technology' , code: 'MU')
Stock.create(name:'Nokia' , code: 'NOK')
Stock.create(name:'Oracle' , code: 'ORCL')
Stock.create(name:'VeriFone' , code: 'PAY')
Stock.create(name:'Priceline' , code: 'PCLN')
Stock.create(name:'Popeyes Louisiana Kitchen' , code: 'PLKI')
Stock.create(name:'Pall' , code: 'PLL')
Stock.create(name:'Plug Power' , code: 'PLUG')
Stock.create(name:'Perrigo' , code: 'PRGO')
Stock.create(name:'PVH Corp' , code: 'PVH')
Stock.create(name:'Qualcomm' , code: 'QCOM')
Stock.create(name:'Royal Dutch Shell' , code: 'RDS-A')
Stock.create(name:'Ralph Lauren' , code: 'RL')
Stock.create(name:'Ross Stores' , code: 'ROST')
Stock.create(name:'Rockwell Medical' , code: 'RMTI')
Stock.create(name:'Raytheon' , code: 'RTN')
Stock.create(name:'Sanmina' , code: 'SANM')
Stock.create(name:'Shake Shack' , code: 'SHAK')
Stock.create(name:'SanDisk' , code: 'SNDK')
Stock.create(name:'Sunesis Pharmaceuticals' , code: 'SNSS')
Stock.create(name:'SunPower' , code: 'SPWR')
Stock.create(name:'Stratasys' , code: 'SSYS')
Stock.create(name:'Seagate Technology' , code: 'STX')
Stock.create(name:'Skyworks Solutions' , code: 'SWKS')
Stock.create(name:'Molson Coors Brewing' , code: 'TAP')
Stock.create(name:'Target' , code: 'TGT')
Stock.create(name:'Talisman Energy' , code: 'TLT')
Stock.create(name:'Toyota Motor Corp' , code: 'TM')
Stock.create(name:'Toll Brothers' , code: 'TOL')
Stock.create(name:'TripAdvisor' , code: 'TRIP')
Stock.create(name:'Tesla Motors' , code: 'TSLA')
Stock.create(name:'Tesoro' , code: 'TSO')
Stock.create(name:'Twitter' , code: 'TWTR')
Stock.create(name:'Under Armour' , code: 'UA')
Stock.create(name:'UPS' , code: 'UPS')
Stock.create(name:'United Rentals' , code: 'URI')
Stock.create(name:'United States Oil Fund' , code: 'USO')
Stock.create(name:'Visteon' , code: 'VC')
Stock.create(name:'Wells Fargo' , code: 'WFC')
Stock.create(name:'Whole Foods Market' , code: 'WFM')
Stock.create(name:'Windstream Holdings' , code: 'WIN')
Stock.create(name:'Waste Management' , code: 'WM')
Stock.create(name:'Wal-Mart' , code: 'WMT')
Stock.create(name:'WhiteWave Foods' , code: 'WWAV')
Stock.create(name:'Wynn Resorts' , code: 'WYNN')
Stock.create(name:'Xilinx' , code: 'XLNX')
Stock.create(name:'Select Sector SPDR-Utilities' , code: 'XLU')
Stock.create(name:'Exxon Mobil' , code: 'XOM')
Stock.create(name:'Yelp' , code: 'YELP')
Stock.create(name:'Yahoo' , code: 'YHOO')
Stock.create(name:'Yum Brands' , code: 'YUM')
Stock.create(name:'Zoes Kitchen' , code: 'ZOES')

StockValue.populate_values
StockValue.populate_values(true)

StockValue.post_fill_rsi_values
