Stock.create(name:'Fastenal' , code: 'FAST')
Stock.create(name:'Facebook' , code: 'FB')
Stock.create(name:'FireEye' , code: 'FEYE')
Stock.create(name:'Finisar' , code: 'FNSR')
Stock.create(name:'Fossil Group' , code: 'FOSL')
Stock.create(name:'First Solar' , code: 'FSLR')
Stock.create(name:'Fortinet' , code: 'FTNT')
Stock.create(name:'Gilead Sciences' , code: 'GILD')
Stock.create(name:'Gold' , code: 'GOLD')
Stock.create(name:'Keurig Green Mountain' , code: 'GMCR')
Stock.create(name:'GoPro' , code: 'GPRO')
Stock.create(name:'Garmin' , code: 'GRMN')
Stock.create(name:'Goodyear Tire' , code: 'GT')
Stock.create(name:'Blackhawk Network Holdings' , code: 'HAWK')
Stock.create(name:'Honda Motor' , code: 'HMC')
Stock.create(name:'Hewlett-Packard' , code: 'HPQ')
Stock.create(name:'Henry Schein' , code: 'HSIC')
Stock.create(name:'Hershey' , code: 'HSY')
Stock.create(name:'iShares Nasdaq Biotechnology' , code: 'IBB')
Stock.create(name:'International Business Machines' , code: 'IBM')
Stock.create(name:'Integrated Device Technology' , code: 'IDTI')
Stock.create(name:'Isis Pharmaceuticals' , code: 'ISIS')
Stock.create(name:'Jack in the Box' , code: 'JACK')
Stock.create(name:'Kellogg' , code: 'K')
Stock.create(name:'Kimberly-Clark' , code: 'KMB')
Stock.create(name:'Kinder Morgan' , code: 'KMI')
Stock.create(name:'Michael Kors Holdings' , code: 'KORS')
Stock.create(name:'Kroger' , code: 'KR')
Stock.create(name:'L Brands' , code: 'LB')
Stock.create(name:'Lenovo' , code: 'LNVGY')

StockValue.post_fill_rsi_values
